# Generated by Django 5.1.5 on 2025-02-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media_home/1')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
