# Generated by Django 5.1.5 on 2025-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInteriors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='categories/1')),
            ],
        ),
        migrations.DeleteModel(
            name='home',
        ),
    ]
