# Generated by Django 5.1.5 on 2025-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_delete_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='categories/2')),
            ],
        ),
    ]
