# Generated by Django 5.1.5 on 2025-02-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_homeinteriors_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateogries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='kitchen/1')),
                ('dimensions', models.IntegerField()),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.homeinteriors')),
            ],
        ),
    ]
