# Generated by Django 5.1.5 on 2025-02-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateogries',
            name='desc',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='cateogries',
            name='dimensions',
            field=models.CharField(max_length=20),
        ),
    ]
