# Generated by Django 5.1.5 on 2025-02-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_business'),
        ('category', '0002_alter_cateogries_desc_alter_cateogries_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Cateogries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='kitchen/1')),
                ('dimensions', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=450)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
        ),
    ]
