# Generated by Django 5.1.5 on 2025-03-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('category_name', models.CharField(max_length=100)),
                ('whatsapp_updates', models.BooleanField(default=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
